# Generated by Django 5.2.12 on 2026-03-23 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category_type', models.CharField(choices=[('behavioral', 'Behavioral'), ('performance', 'Performance')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('self_submitted', 'Self Submitted'), ('manager_review', 'Manager Review'), ('completed', 'Completed')], default='draft', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('review_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.reviewcycle')),
            ],
            options={
                'unique_together': {('employee', 'review_cycle')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeQuestionnaireStageSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluator_type', models.CharField(choices=[('self', 'Self'), ('reporting_manager', 'Reporting Manager'), ('skip_level_manager', 'Skip Level Manager'), ('peer', 'Peer')], max_length=50)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('scope_of_improvement', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('employee_questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.employeequestionnaire')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('employee_questionnaire', 'evaluator_type')},
            },
        ),
        migrations.CreateModel(
            name='QuestionParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('department', models.CharField(blank=True, max_length=150, null=True)),
                ('default_weightage', models.FloatField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='evaluations.questioncategory')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeQuestionnaireItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weightage', models.FloatField(default=1)),
                ('order', models.IntegerField(default=0)),
                ('employee_questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='evaluations.employeequestionnaire')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.questionparameter')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeQuestionnaireResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('questionnaire_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.employeequestionnaireitem')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='evaluations.employeequestionnairestagesubmission')),
            ],
            options={
                'unique_together': {('submission', 'questionnaire_item')},
            },
        ),
    ]
