# Generated by Django 5.2.12 on 2026-03-23 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeequestionnaireitem',
            unique_together={('employee_questionnaire', 'parameter')},
        ),
    ]
