# Generated by Django 5.2.12 on 2026-03-23 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_alter_employeequestionnaireitem_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeequestionnaire',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='employeequestionnaire',
            name='peer_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeequestionnaire',
            name='peer_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peer_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeequestionnaire',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeequestionnaire',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('self_submitted', 'Self Submitted'), ('under_rm_review', 'Under RM Review'), ('rm_reviewed', 'RM Reviewed'), ('under_skip_review', 'Under Skip Review'), ('skip_reviewed', 'Skip Reviewed')], default='draft', max_length=50),
        ),
    ]
