# Generated by Django 5.2.12 on 2026-03-23 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0003_alter_employeequestionnaire_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeequestionnaireresponse',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='employeequestionnaireresponse',
            name='reviewer_type',
            field=models.CharField(choices=[('self', 'Self'), ('rm', 'Reporting Manager'), ('skip', 'Skip Manager'), ('peer', 'Peer')], default='self', max_length=20),
        ),
        migrations.AlterField(
            model_name='employeequestionnaireresponse',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.employeequestionnairestagesubmission'),
        ),
    ]
