# Generated by Django 5.2.12 on 2026-03-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0004_alter_employeequestionnaireresponse_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeequestionnaire',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('self_submitted', 'Self Submitted'), ('under_rm_review', 'Under RM Review'), ('rm_reviewed', 'RM Reviewed'), ('under_skip_review', 'Under Skip Review'), ('skip_reviewed', 'Skip Reviewed'), ('under_peer_review', 'Under Peer Review'), ('completed', 'Completed')], default='draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='employeequestionnairestagesubmission',
            name='evaluator_type',
            field=models.CharField(choices=[('self', 'Self'), ('rm', 'Reporting Manager'), ('skip', 'Skip Level Manager'), ('peer', 'Peer')], max_length=20),
        ),
    ]
