# Generated by Django 5.2.12 on 2026-03-26 18:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0005_alter_employeequestionnaire_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeequestionnaire',
            unique_together={('employee', 'review_cycle')},
        ),
    ]
