# Generated by Django 5.2.12 on 2026-03-27 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0006_alter_employeequestionnaire_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeequestionnaireresponse',
            unique_together={('submission', 'questionnaire_item', 'reviewer_type')},
        ),
    ]
