# Generated by Django 5.2.12 on 2026-03-24 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluations', '0005_alter_employeequestionnaire_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Configuration', max_length=100)),
                ('behavioural_weight', models.FloatField(default=0.4)),
                ('performance_weight', models.FloatField(default=0.6)),
                ('self_weight', models.FloatField(default=0.1)),
                ('rm_weight', models.FloatField(default=0.5)),
                ('skip_weight', models.FloatField(default=0.25)),
                ('peer_weight', models.FloatField(default=0.15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePerformanceScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_behavioural_score', models.FloatField(blank=True, null=True)),
                ('self_performance_score', models.FloatField(blank=True, null=True)),
                ('rm_behavioural_score', models.FloatField(blank=True, null=True)),
                ('rm_performance_score', models.FloatField(blank=True, null=True)),
                ('skip_behavioural_score', models.FloatField(blank=True, null=True)),
                ('skip_performance_score', models.FloatField(blank=True, null=True)),
                ('peer_behavioural_score', models.FloatField(blank=True, null=True)),
                ('peer_performance_score', models.FloatField(blank=True, null=True)),
                ('self_score', models.FloatField(blank=True, null=True)),
                ('rm_score', models.FloatField(blank=True, null=True)),
                ('skip_score', models.FloatField(blank=True, null=True)),
                ('peer_score', models.FloatField(blank=True, null=True)),
                ('effective_self_weight', models.FloatField(blank=True, null=True)),
                ('effective_rm_weight', models.FloatField(blank=True, null=True)),
                ('effective_skip_weight', models.FloatField(blank=True, null=True)),
                ('effective_peer_weight', models.FloatField(blank=True, null=True)),
                ('system_final_score', models.FloatField(blank=True, null=True)),
                ('hr_override_score', models.FloatField(blank=True, null=True)),
                ('final_effective_score', models.FloatField(blank=True, null=True)),
                ('override_reason', models.TextField(blank=True, null=True)),
                ('overridden_at', models.DateTimeField(blank=True, null=True)),
                ('is_released_to_employee', models.BooleanField(default=False)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('employee_questionnaire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='evaluations.employeequestionnaire')),
                ('overridden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_overrides', to=settings.AUTH_USER_MODEL)),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_scores', to=settings.AUTH_USER_MODEL)),
                ('review_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.reviewcycle')),
            ],
        ),
    ]
