# Generated by Django 5.2.12 on 2026-03-25 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeperformancescore',
            name='nine_box_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeperformancescore',
            name='potential_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
