# Generated by Django 5.2.12 on 2026-03-25 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0005_alter_employeequestionnaire_status_and_more'),
        ('scoring', '0002_employeeperformancescore_nine_box_label_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePastPerformanceIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_cycle_score', models.FloatField()),
                ('previous_cycle_score_1', models.FloatField(blank=True, null=True)),
                ('previous_cycle_score_2', models.FloatField(blank=True, null=True)),
                ('ppi_score', models.FloatField()),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('review_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.reviewcycle')),
            ],
            options={
                'unique_together': {('employee', 'review_cycle')},
            },
        ),
    ]
