# Generated by Django 5.2.12 on 2026-03-25 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0005_alter_employeequestionnaire_status_and_more'),
        ('scoring', '0003_employeepastperformanceindex'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PotentialParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('weightage', models.FloatField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PotentialScoreConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Potential Config', max_length=100)),
                ('rm_weight', models.FloatField(default=0.6)),
                ('skip_weight', models.FloatField(default=0.4)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePotentialAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rm_submitted', models.BooleanField(default=False)),
                ('skip_submitted', models.BooleanField(default=False)),
                ('status', models.CharField(default='pending_rm', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('employee_questionnaire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='evaluations.employeequestionnaire')),
                ('review_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.reviewcycle')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePotentialScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rm_score', models.FloatField(blank=True, null=True)),
                ('skip_score', models.FloatField(blank=True, null=True)),
                ('final_potential_score', models.FloatField()),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('employee_questionnaire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='evaluations.employeequestionnaire')),
                ('review_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.reviewcycle')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePotentialResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluator_type', models.CharField(choices=[('rm', 'RM'), ('skip', 'Skip Manager')], max_length=10)),
                ('score', models.FloatField()),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoring.employeepotentialassessment')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoring.potentialparameter')),
            ],
        ),
    ]
