# Generated by Django 5.2.12 on 2026-03-25 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0005_alter_employeequestionnaire_status_and_more'),
        ('scoring', '0004_potentialparameter_potentialscoreconfiguration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeNineBoxPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppi_score', models.FloatField()),
                ('potential_score', models.FloatField()),
                ('performance_bucket', models.CharField(max_length=20)),
                ('potential_bucket', models.CharField(max_length=20)),
                ('box_label', models.CharField(max_length=100)),
                ('box_description', models.TextField()),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('employee_questionnaire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='evaluations.employeequestionnaire')),
                ('review_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.reviewcycle')),
            ],
        ),
    ]
