# Generated by Django 5.2.12 on 2026-03-25 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0005_alter_employeequestionnaire_status_and_more'),
        ('scoring', '0005_employeenineboxplacement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppraisalRecommendationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_label', models.CharField(max_length=100, unique=True)),
                ('min_percent', models.FloatField()),
                ('max_percent', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAppraisalRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppi_score_used', models.FloatField()),
                ('potential_score_used', models.FloatField()),
                ('box_label', models.CharField(max_length=100)),
                ('min_appraisal_percent', models.FloatField()),
                ('max_appraisal_percent', models.FloatField()),
                ('suggested_appraisal_percent', models.FloatField()),
                ('hr_override_percent', models.FloatField(blank=True, null=True)),
                ('override_reason', models.TextField(blank=True, null=True)),
                ('overridden_at', models.DateTimeField(blank=True, null=True)),
                ('final_effective_appraisal_percent', models.FloatField()),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('employee_questionnaire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='evaluations.employeequestionnaire')),
                ('nine_box_placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoring.employeenineboxplacement')),
                ('overridden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appraisal_overrides', to=settings.AUTH_USER_MODEL)),
                ('review_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.reviewcycle')),
            ],
        ),
    ]
