# Generated by Django 5.2.12 on 2026-03-25 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0005_alter_employeequestionnaire_status_and_more'),
        ('scoring', '0006_appraisalrecommendationconfig_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAnalyticsRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_released_to_employee', models.BooleanField(default=False)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('unreleased_at', models.DateTimeField(blank=True, null=True)),
                ('show_performance_score', models.BooleanField(default=True)),
                ('show_ppi', models.BooleanField(default=True)),
                ('show_potential_score', models.BooleanField(default=True)),
                ('show_nine_box', models.BooleanField(default=True)),
                ('show_self_feedback', models.BooleanField(default=True)),
                ('show_rm_feedback', models.BooleanField(default=True)),
                ('show_skip_feedback', models.BooleanField(default=True)),
                ('show_peer_feedback', models.BooleanField(default=True)),
                ('show_self_scope_of_improvement', models.BooleanField(default=True)),
                ('show_rm_scope_of_improvement', models.BooleanField(default=True)),
                ('show_skip_scope_of_improvement', models.BooleanField(default=True)),
                ('show_peer_scope_of_improvement', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_questionnaire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_release', to='evaluations.employeequestionnaire')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_employee_analytics', to=settings.AUTH_USER_MODEL)),
                ('unreleased_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unreleased_employee_analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employee_analytics_release',
            },
        ),
    ]
